[nodes]
leios_node

[nodes:vars]
ansible_host="{{ lookup('env', 'VPS_IP') | default(local_vps_ip, true) }}"
ansible_user="{{ lookup('env', 'VPS_USERNAME') | default(local_vps_username, true) }}"
ansible_ssh_private_key_file="~/.ssh/leios_deploy_key"
ansible_python_interpreter="/usr/bin/python3.10"